#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

# 克隆环境，避免影响其他模块
env_game = env_modules.Clone()

# 添加源文件到编译列表
env_game.add_source_files(env.modules_sources, "*.cpp")

# UI子目录
env_game.add_source_files(env.modules_sources, "ui/*.cpp")
