#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

# 克隆环境，避免影响其他模块
env_game = env_modules.Clone()

# 只添加核心数据层文件
module_obj = []

# WorldManager - 管理接口
module_obj.append(env_game.Object("world_manager.cpp"))

# World 和 Chunk - 纯地形数据管理
module_obj.append(env_game.Object("world.cpp"))
module_obj.append(env_game.Object("chunk.cpp"))
module_obj.append(env_game.Object("town_generator.cpp"))

# ItemManager - 物品系统
module_obj.append(env_game.Object("item/item.cpp"))
module_obj.append(env_game.Object("item/item_manager.cpp"))

# 模块注册
module_obj.append(env_game.Object("register_types.cpp"))

env.modules_sources += module_obj
